version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-for-cafe
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: cafe_admin
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: cafe_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-cafe-volume:/var/lib/mysql
    restart: always  # Tự động khởi động lại container nếu bị tắt

volumes:
  mysql-cafe-volume: